version: 2.1

#ここに指定しているものは繰り返しすかうことができる。
anchor:
  hello_place_anchor: &hello_place_anchor
    parameters:
      env:
        type: string
    steps:
      - run:
          command: echo Hello, << parameters.env >>
executors:
  hello_executor:
    docker:
      - image: cimg/base:<<parameters.tag>>
    parameters:
      tag:
        default: "2021.07"
        type: string
jobs: 
  hello_use_anchor:
      <<: *hello_place_anchor
      executor:
        name: hello_executor
workflows:
  hello_use_anchor:
    jobs:
      - hello_use_anchor:
          name: echo_tokyo
          env: "Osaka"
